### ISSUE TITLE
catkin_make compilation fail

### ISSUE THREAD

**Issue by RicardoRagel** [tesYolan/cmt_tracker#2]
Hi Tesfa,

I am tryiing to compile the cmt_tracker in ROS Indigo (Ubuntu 14.04).

Clonning the repository and making "catkin_make" I get the next error in the terminal:

```
<...> /cmt_tracker/src/cmt_tracker_node.cpp:19:17: fatal error: CMT.h: No existe el archivo o el directorio
 #include "CMT.h"
                 
compilation terminated.
```
Could you help me? Do I need to install some dependencies (CMT algorithm)?

Thank you very much!

**Comment by tesYolan** [comment]
Hi; Sorry for the delayed response; You need to have installed https://github.com/tesYolan/CppMT as this code is a wrapper around that one.

**Comment by RicardoRagel** [comment]
Hi! Thank you for your response. I compiled this CMT code and include it in the cmt_tracker ROS package, but now I get the next error (and some more):

error: ‘class cmt::CMT’ has no member named ‘initialized’

I checked that CMT.h and CMT.cpp does not include this variable in the class.

Thanks!

**Comment by tesYolan** [comment]
Oh; I forgot; it's in the wrapper branch. 

If you are interested in cmt_tracker wrapper for ROS; I would advise you as the most recent changes and configuration are available at https://github.com/hansonrobotics/HEAD/tree/master/src/vision/cmt_tracker 

You don't particularly need to install most of the packages; but you can follow https://github.com/hansonrobotics/HEAD/blob/master/scripts/hrtool#L695 as it does illustrate all of the necessary packages to install. 

Note; This package is used to track face after they have been detected by one of the opencv/dlib packages. 

Regards







    On Monday, March 13, 2017 12:12 PM, Ricardo Ragel de la Torre <notifications@github.com> wrote:
 

 Hi! Thank you for your response. I compiled this CMT code and include it in the cmt_tracker ROS package, but now I get the next error (and some more):error: ‘class cmt::CMT’ has no member named ‘initialized’I checked that CMT.h and CMT.cpp does not include this variable in the class.Thanks!—

**Comment by RicardoRagel** [comment]
Perfect! Thank you very much Tesfa. Finally, I have created my own ROS package wrapper using the CppMT library, it works very well :) .

Very grateful for your reply!
